"""Create Issue model

Revision ID: 74e1b7887bb4
Revises:
Create Date: 2025-07-15 08:53:06.280403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74e1b7887bb4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("open", "closed", name="statusenum"), nullable=False
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum("positive", "negative", "neutral", "unknown", name="sentimentenum"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "техническая",
                "оплата",
                "другое",
                name="categoryenum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issues")
    # ### end Alembic commands ###
