"""Add geo field to Issue model

Revision ID: c9d8babf62fa
Revises: 74e1b7887bb4
Create Date: 2025-07-16 21:11:13.300117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d8babf62fa"
down_revision: Union[str, Sequence[str], None] = "74e1b7887bb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues", sa.Column("geo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issues", "geo")
    # ### end Alembic commands ###
